const numsRow = [
    {
        caseDownRu: 'ё',
        caseUpRu: 'Ё',
        capsRu: 'Ё',
        shiftCapsRu: 'ё',
        caseDownEn: '`',
        caseUpEn: '~',
        capsEn: '`',
        shiftCaps: '~',
        name: 'Backquote',
    },
    {
        caseDownRu: '1',
        caseUpRu: '!',
        capsRu: '1',
        shiftCapsRu: '!',
        caseDownEn: '1',
        caseUpEn: '!',
        capsEn: '1',
        shiftCaps: '!',
        name: 'Digit1',
    },
    {
        caseDownRu: '2',
        caseUpRu: '"',
        capsRu: '2',
        shiftCapsRu: '"',
        caseDownEn: '2',
        caseUpEn: '@',
        capsEn: '2',
        shiftCaps: '@',
        name: 'Digit2',
    },
    {
        caseDownRu: '3',
        caseUpRu: '№',
        capsRu: '3',
        shiftCapsRu: '№',
        caseDownEn: '3',
        caseUpEn: '#',
        capsEn: '3',
        shiftCaps: '#',
        name: 'Digit3',
    },
    {
        caseDownRu: '4',
        caseUpRu: ';',
        capsRu: '4',
        shiftCapsRu: ';',
        caseDownEn: '4',
        caseUpEn: '$',
        capsEn: '4',
        shiftCaps: '$',
        name: 'Digit4',
    },
    {
        caseDownRu: '5',
        caseUpRu: '%',
        capsRu: '5',
        shiftCapsRu: '%',
        caseDownEn: '5',
        caseUpEn: '%',
        capsEn: '5',
        shiftCaps: '%',
        name: 'Digit5',
    },
    {
        caseDownRu: '6',
        caseUpRu: ':',
        capsRu: '6',
        shiftCapsRu: ':',
        caseDownEn: '6',
        caseUpEn: '^',
        capsEn: '6',
        shiftCaps: '^',
        name: 'Digit6',
    },
    {
        caseDownRu: '7',
        caseUpRu: '?',
        capsRu: '7',
        shiftCapsRu: '?',
        caseDownEn: '7',
        caseUpEn: '&',
        capsEn: '7',
        shiftCaps: '&',
        name: 'Digit7',
    },
    {
        caseDownRu: '8',
        caseUpRu: '*',
        capsRu: '8',
        shiftCapsRu: '*',
        caseDownEn: '8',
        caseUpEn: '*',
        capsEn: '8',
        shiftCaps: '*',
        name: 'Digit8',
    },
    {
        caseDownRu: '9',
        caseUpRu: '(',
        capsRu: '9',
        shiftCapsRu: '(',
        caseDownEn: '9',
        caseUpEn: '(',
        capsEn: '9',
        shiftCaps: '(',
        name: 'Digit9',
    },
    {
        caseDownRu: '0',
        caseUpRu: ')',
        capsRu: '0',
        shiftCapsRu: ')',
        caseDownEn: '0',
        caseUpEn: ')',
        capsEn: '0',
        shiftCaps: ')',
        name: 'Digit0',
    },
    {
        caseDownRu: '-',
        caseUpRu: '_',
        capsRu: '-',
        shiftCapsRu: '_',
        caseDownEn: '-',
        caseUpEn: '_',
        capsEn: '-',
        shiftCaps: '_',
        name: 'Minus',
    },
    {
        caseDownRu: '=',
        caseUpRu: '+',
        capsRu: '=',
        shiftCapsRu: '+',
        caseDownEn: '=',
        caseUpEn: '+',
        capsEn: '=',
        shiftCaps: '+',
        name: 'Equal',
    },
    {
        caseDownRu: 'Backspace',
        caseUpRu: 'Backspace',
        capsRu: 'Backspace',
        shiftCapsRu: 'Backspace',
        caseDownEn: 'Backspace',
        caseUpEn: 'Backspace',
        capsEn: 'Backspace',
        shiftCaps: 'Backspace',
        name: 'Backspace',
    },
];

const tabRow = [
    {
        caseDownRu: 'Tab',
        caseUpRu: 'Tab',
        capsRu: 'Tab',
        shiftCapsRu: 'Tab',
        caseDownEn: 'Tab',
        caseUpEn: 'Tab',
        capsEn: 'Tab',
        shiftCaps: 'Tab',
        name: 'Tab',
    },
    {
        caseDownRu: 'й',
        caseUpRu: 'Й',
        capsRu: 'Й',
        shiftCapsRu: 'й',
        caseDownEn: 'q',
        caseUpEn: 'Q',
        capsEn: 'Q',
        shiftCaps: 'q',
        name: 'KeyQ',
    },
    {
        caseDownRu: 'ц',
        caseUpRu: 'Ц',
        capsRu: 'Ц',
        shiftCapsRu: 'ц',
        caseDownEn: 'w',
        caseUpEn: 'W',
        capsEn: 'W',
        shiftCaps: 'w',
        name: 'KeyW',
    },
    {
        caseDownRu: 'у',
        caseUpRu: 'У',
        capsRu: 'У',
        shiftCapsRu: 'у',
        caseDownEn: 'e',
        caseUpEn: 'E',
        capsEn: 'E',
        shiftCaps: 'e',
        name: 'KeyE',
    },
    {
        caseDownRu: 'к',
        caseUpRu: 'К',
        capsRu: 'К',
        shiftCapsRu: 'к',
        caseDownEn: 'r',
        caseUpEn: 'R',
        capsEn: 'R',
        shiftCaps: 'r',
        name: 'KeyR',
    },
    {
        caseDownRu: 'е',
        caseUpRu: 'Е',
        capsRu: 'Е',
        shiftCapsRu: 'е',
        caseDownEn: 't',
        caseUpEn: 'T',
        capsEn: 'T',
        shiftCaps: 't',
        name: 'KeyT',
    },
    {
        caseDownRu: 'н',
        caseUpRu: 'Н',
        capsRu: 'Н',
        shiftCapsRu: 'н',
        caseDownEn: 'y',
        caseUpEn: 'Y',
        capsEn: 'Y',
        shiftCaps: 'y',
        name: 'KeyY',
    },
    {
        caseDownRu: 'г',
        caseUpRu: 'Г',
        capsRu: 'Г',
        shiftCapsRu: 'г',
        caseDownEn: 'u',
        caseUpEn: 'U',
        capsEn: 'U',
        shiftCaps: 'u',
        name: 'KeyU',
    },
    {
        caseDownRu: 'ш',
        caseUpRu: 'Ш',
        capsRu: 'Ш',
        shiftCapsRu: 'ш',
        caseDownEn: 'i',
        caseUpEn: 'I',
        capsEn: 'I',
        shiftCaps: 'i',
        name: 'KeyI',
    },
    {
        caseDownRu: 'щ',
        caseUpRu: 'Щ',
        capsRu: 'Щ',
        shiftCapsRu: 'щ',
        caseDownEn: 'o',
        caseUpEn: 'O',
        capsEn: 'O',
        shiftCaps: 'o',
        name: 'KeyO',
    },
    {
        caseDownRu: 'з',
        caseUpRu: 'З',
        capsRu: 'З',
        shiftCapsRu: 'з',
        caseDownEn: 'p',
        caseUpEn: 'P',
        capsEn: 'P',
        shiftCaps: 'p',
        name: 'KeyP',
    },
    {
        caseDownRu: 'х',
        caseUpRu: 'Х',
        capsRu: 'Х',
        shiftCapsRu: 'х',
        caseDownEn: '[',
        caseUpEn: '{',
        capsEn: '[',
        shiftCaps: '{',
        name: 'BracketLeft',
    },
    {
        caseDownRu: 'ъ',
        caseUpRu: 'Ъ',
        capsRu: 'Ъ',
        shiftCapsRu: 'ъ',
        caseDownEn: ']',
        caseUpEn: '}',
        capsEn: ']',
        shiftCaps: '}',
        name: 'BracketRight',
    },
    {
        caseDownRu: "\u005C",
        caseUpRu: '/',
        capsRu: '\u005C',
        shiftCapsRu: '/',
        caseDownEn: '\u005C',
        caseUpEn: '|',
        capsEn: '\u005C',
        shiftCaps: '|',
        name: 'Backslash',
    },
    {
        caseDownRu: 'Del',
        caseUpRu: 'Del',
        capsRu: 'Del',
        shiftCapsRu: 'Del',
        caseDownEn: 'Del',
        caseUpEn: 'Del',
        capsEn: 'Del',
        shiftCaps: 'Del',
        name: 'Delete',
    },
];

const capsRow = [
    {
        caseDownRu: 'CapsLock',
        caseUpRu: 'CapsLock',
        capsRu: 'CapsLock',
        shiftCapsRu: 'CapsLock',
        caseDownEn: 'CapsLock',
        caseUpEn: 'CapsLock',
        capsEn: 'CapsLock',
        shiftCaps: 'CapsLock',
        name: 'CapsLock',
    },
    {
        caseDownRu: 'ф',
        caseUpRu: 'Ф',
        capsRu: 'Ф',
        shiftCapsRu: 'ф',
        caseDownEn: 'a',
        caseUpEn: 'A',
        capsEn: 'A',
        shiftCaps: 'a',
        name: 'KeyA',
    },
    {
        caseDownRu: 'ы',
        caseUpRu: 'Ы',
        capsRu: 'Ы',
        shiftCapsRu: 'ы',
        caseDownEn: 's',
        caseUpEn: 'S',
        capsEn: 'S',
        shiftCaps: 's',
        name: 'KeyS',
    },
    {
        caseDownRu: 'в',
        caseUpRu: 'В',
        capsRu: 'В',
        shiftCapsRu: 'в',
        caseDownEn: 'd',
        caseUpEn: 'D',
        capsEn: 'D',
        shiftCaps: 'd',
        name: 'KeyD',
    },
    {
        caseDownRu: 'а',
        caseUpRu: 'А',
        capsRu: 'А',
        shiftCapsRu: 'а',
        caseDownEn: 'f',
        caseUpEn: 'F',
        capsEn: 'F',
        shiftCaps: 'f',
        name: 'KeyF',
    },
    {
        caseDownRu: 'п',
        caseUpRu: 'П',
        capsRu: 'П',
        shiftCapsRu: 'п',
        caseDownEn: 'g',
        caseUpEn: 'G',
        capsEn: 'G',
        shiftCaps: 'g',
        name: 'KeyG',
    },
    {
        caseDownRu: 'р',
        caseUpRu: 'Р',
        capsRu: 'Р',
        shiftCapsRu: 'р',
        caseDownEn: 'h',
        caseUpEn: 'H',
        capsEn: 'H',
        shiftCaps: 'h',
        name: 'KeyH',
    },
    {
        caseDownRu: 'о',
        caseUpRu: 'О',
        capsRu: 'О',
        shiftCapsRu: 'о',
        caseDownEn: 'j',
        caseUpEn: 'J',
        capsEn: 'J',
        shiftCaps: 'j',
        name: 'KeyJ',
    },
    {
        caseDownRu: 'л',
        caseUpRu: 'Л',
        capsRu: 'Л',
        shiftCapsRu: 'л',
        caseDownEn: 'k',
        caseUpEn: 'K',
        capsEn: 'K',
        shiftCaps: 'k',
        name: 'KeyK',
    },
    {
        caseDownRu: 'д',
        caseUpRu: 'Д',
        capsRu: 'Д',
        shiftCapsRu: 'д',
        caseDownEn: 'l',
        caseUpEn: 'L',
        capsEn: 'L',
        shiftCaps: 'l',
        name: 'KeyL',
    },
    {
        caseDownRu: 'ж',
        caseUpRu: 'Ж',
        capsRu: 'Ж',
        shiftCapsRu: 'ж',
        caseDownEn: ';',
        caseUpEn: ':',
        capsEn: ';',
        shiftCaps: ':',
        name: 'Semicolon',
    },
    {
        caseDownRu: 'э',
        caseUpRu: 'Э',
        capsRu: 'Э',
        shiftCapsRu: 'э',
        caseDownEn: "'",
        caseUpEn: '"',
        capsEn: "'",
        shiftCaps: '"',
        name: 'Quote',
    },
    {
        caseDownRu: 'Enter',
        caseUpRu: 'Enter',
        capsRu: 'Enter',
        shiftCapsRu: 'Enter',
        caseDownEn: 'Enter',
        caseUpEn: 'Enter',
        capsEn: 'Enter',
        shiftCaps: 'Enter',
        name: 'Enter',
    },
];

const shiftRow = [
    {
        caseDownRu: 'Shift',
        caseUpRu: 'Shift',
        capsRu: 'Shift',
        shiftCapsRu: 'Shift',
        caseDownEn: 'Shift',
        caseUpEn: 'Shift',
        capsEn: 'Shift',
        shiftCaps: 'Shift',
        name: 'ShiftLeft',
    },
    {
        caseDownRu: 'я',
        caseUpRu: 'Я',
        capsRu: 'Я',
        shiftCapsRu: 'я',
        caseDownEn: 'z',
        caseUpEn: 'Z',
        capsEn: 'Z',
        shiftCaps: 'z',
        name: 'KeyZ',
    },
    {
        caseDownRu: 'ч',
        caseUpRu: 'Ч',
        capsRu: 'Ч',
        shiftCapsRu: 'ч',
        caseDownEn: 'x',
        caseUpEn: 'X',
        capsEn: 'X',
        shiftCaps: 'x',
        name: 'KeyX',
    },
    {
        caseDownRu: 'с',
        caseUpRu: 'С',
        capsRu: 'С',
        shiftCapsRu: 'с',
        caseDownEn: 'c',
        caseUpEn: 'C',
        capsEn: 'C',
        shiftCaps: 'c',
        name: 'KeyC',
    },
    {
        caseDownRu: 'м',
        caseUpRu: 'М',
        capsRu: 'М',
        shiftCapsRu: 'м',
        caseDownEn: 'v',
        caseUpEn: 'V',
        capsEn: 'V',
        shiftCaps: 'v',
        name: 'KeyV',
    },
    {
        caseDownRu: 'и',
        caseUpRu: 'И',
        capsRu: 'И',
        shiftCapsRu: 'и',
        caseDownEn: 'b',
        caseUpEn: 'B',
        capsEn: 'B',
        shiftCaps: 'b',
        name: 'KeyB',
    },
    {
        caseDownRu: 'т',
        caseUpRu: 'Т',
        capsRu: 'Т',
        shiftCapsRu: 'т',
        caseDownEn: 'n',
        caseUpEn: 'N',
        capsEn: 'N',
        shiftCaps: 'n',
        name: 'KeyN',
    },
    {
        caseDownRu: 'ь',
        caseUpRu: 'Ь',
        capsRu: 'Ь',
        shiftCapsRu: 'ь',
        caseDownEn: 'm',
        caseUpEn: 'M',
        capsEn: 'M',
        shiftCaps: 'm',
        name: 'KeyM',
    },
    {
        caseDownRu: 'б',
        caseUpRu: 'Б',
        capsRu: 'Б',
        shiftCapsRu: 'б',
        caseDownEn: ',',
        caseUpEn: '<',
        capsEn: ',',
        shiftCaps: '<',
        name: 'Comma',
    },
    {
        caseDownRu: 'ю',
        caseUpRu: 'Ю',
        capsRu: 'Ю',
        shiftCapsRu: 'ю',
        caseDownEn: '.',
        caseUpEn: '>',
        capsEn: '.',
        shiftCaps: '>',
        name: 'Period',
    },
    {
        caseDownRu: '.',
        caseUpRu: ',',
        capsRu: '.',
        shiftCapsRu: ',',
        caseDownEn: '/',
        caseUpEn: '?',
        capsEn: '/',
        shiftCaps: '?',
        name: 'Slash',
    },
    {
        caseDownRu: '▲',
        caseUpRu: '▲',
        capsRu: '▲',
        shiftCapsRu: '▲',
        caseDownEn: '▲',
        caseUpEn: '▲',
        capsEn: '▲',
        shiftCaps: '▲',
        name: 'ArrowUp',
    },
    {
        caseDownRu: 'Shift',
        caseUpRu: 'Shift',
        capsRu: 'Shift',
        shiftCapsRu: 'Shift',
        caseDownEn: 'Shift',
        caseUpEn: 'Shift',
        capsEn: 'Shift',
        shiftCaps: 'Shift',
        name: 'ShiftRight',
    },
];

const ctrlRow = [
    {
        caseDownRu: 'Ctrl',
        caseUpRu: 'Ctrl',
        capsRu: 'Ctrl',
        shiftCapsRu: 'Ctrl',
        caseDownEn: 'Ctrl',
        caseUpEn: 'Ctrl',
        capsEn: 'Ctrl',
        shiftCaps: 'Ctrl',
        name: 'ControlLeft',
    },
    {
        caseDownRu: 'Win',
        caseUpRu: 'Win',
        capsRu: 'Win',
        shiftCapsRu: 'Win',
        caseDownEn: 'Win',
        caseUpEn: 'Win',
        capsEn: 'Win',
        shiftCaps: 'Win',
        name: 'MetaLeft',
    },
    {
        caseDownRu: 'Alt',
        caseUpRu: 'Alt',
        capsRu: 'Alt',
        shiftCapsRu: 'Alt',
        caseDownEn: 'Alt',
        caseUpEn: 'Alt',
        capsEn: 'Alt',
        shiftCaps: 'Alt',
        name: 'AltLeft',
    },
    {
        caseDownRu: '',
        caseUpRu: '',
        capsRu: '',
        shiftCapsRu: '',
        caseDownEn: '',
        caseUpEn: '',
        capsEn: '',
        shiftCaps: '',
        name: 'Space',
    },
    {
        caseDownRu: 'Alt',
        caseUpRu: 'Alt',
        capsRu: 'Alt',
        shiftCapsRu: 'Alt',
        caseDownEn: 'Alt',
        caseUpEn: 'Alt',
        capsEn: 'Alt',
        shiftCaps: 'Alt',
        name: 'AltRight',
    },
    {
        caseDownRu: '◄',
        caseUpRu: '◄',
        capsRu: '◄',
        shiftCapsRu: '◄',
        caseDownEn: '◄',
        caseUpEn: '◄',
        capsEn: '◄',
        shiftCaps: '◄',
        name: 'ArrowLeft',
    },
    {
        caseDownRu: '▼',
        caseUpRu: '▼',
        capsRu: '▼',
        shiftCapsRu: '▼',
        caseDownEn: '▼',
        caseUpEn: '▼',
        capsEn: '▼',
        shiftCaps: '▼',
        name: 'ArrowDown',
    },
    {
        caseDownRu: '►',
        caseUpRu: '►',
        capsRu: '►',
        shiftCapsRu: '►',
        caseDownEn: '►',
        caseUpEn: '►',
        capsEn: '►',
        shiftCaps: '►',
        name: 'ArrowRight',
    },
    {
        caseDownRu: 'Ctrl',
        caseUpRu: 'Ctrl',
        capsRu: 'Ctrl',
        shiftCapsRu: 'Ctrl',
        caseDownEn: 'Ctrl',
        caseUpEn: 'Ctrl',
        capsEn: 'Ctrl',
        shiftCaps: 'Ctrl',
        name: 'ControlRight',
    },
];